### ISSUE TITLE
requirements.txt not working

### ISSUE THREAD

**Issue by keeganstoner** [MelissaChen15/control-vc#1]
The requirements.txt file has some weird text in it, I've never seen a git-lfs url in a requirements file before and it doesn't run with pip.

**Comment by MelissaChen15** [comment]
Hi Keeganstoner, 

Thank you very much for pointing this out! The requirements.txt has been updated!

I use git-lfs to store large txt files in this repo, which changed all txt files, accidentally including requirements.txt, into URL... 

Now you can run it with pip!

Best, 
Melissa
